### PR TITLE
mongodb 3.6 support

### PR DESCRIPTION
**Pull request by Loki-Afro**
fixes gh-223

### CODE REVIEW

**Comment by Loki-Afro** [comment]
Unfortunately the mongodb dev build is kinda broken, its not downloadable at the moment, it will receive an access denied, I suggest to wait a bit with the merge ...

**Comment by dementiacs** [comment]
Any movement on this?

**Comment by Loki-Afro** [comment]
@dementiacs the nightly builds are currently not downloadable at https://www.mongodb.com/download-center#development

however there are (since today?) new development builds available that are downloadable, I'll integrate those later. to let the test go green again ;)

**Comment by dementiacs** [comment]
@Loki-Afro Awesome

**Comment by thetric** [comment]
Could you release a new version, please?

**Comment by Loki-Afro** [comment]
@michaelmosmann could you? ;)

**Comment by crinuc** [comment]
Hello!

Can you please please release?

Thank you!

**Pull request merged**
