### PR TITLE
Added a module providing a standalone downloader & extraction tool for Mongo

### PR DESCRIPTION
**Pull request by laurentgaertner**
Please contact ittaiz@wix.com for additional information

### CODE REVIEW

**Comment by ittaiz** [comment]
Hi @Loki-Afro / @michaelmosmann,
This fixes #205.
I'd appreciate your code review as this gap is blocking us.

**Comment by michaelmosmann** [comment]
... will have a look at this in the evening.

**Comment by ittaiz** [comment]
Thanks!

**Comment by michaelmosmann** [comment]
Ok.. i have some questions: AFAIK your code change... what you want is: provide a tool which downloads the correct artifact for a specific version of mongodb into the correct directory (the place where it should be cached).

This code will do a little bit more than wget or curl.. we could just provide some "uh oh.. could not download xyz.. you can use following command to download this aritfact: curl http:/... /mongodb-v012.tar .embeddedMongo/linux/v012/foo.tar"

Do i miss some points?

**Comment by ittaiz** [comment]
What I want is to have the same ease and speed flapdoodle gives me in non hermetic systems (maven/gradle/etc) which means download and extract.
I want that ease and speed with determinism which is why we want to enable having only this "setup" part separated.
Does that make sense?

**Comment by ittaiz** [comment]
@michaelmosmann friendly ping

**Comment by michaelmosmann** [comment]
It does.

(i am in a hurry... so i hope i can do a release today or tomorrow.. sorry, if this is not as fast as you would like ...)

**Comment by ittaiz** [comment]
That's totally fine. Today or tomorrow that's excellent.
Thank you!

**Comment by Loki-Afro** [comment]
@ittaiz but this does not have to be a module, its kinda standalone project since you didn't need to change any line of code or am I missing any changes?

you could just create a fancy-wix-maven-project which has `de.flapdoodle.embed.mongo` as dependency + that additional class + some maven assembly packaging magic

what I want to say is there is no need for a maven module

**Comment by michaelmosmann** [comment]
after all i did this: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.downloader

i hope, this is the kind of thing you wanted... thanks for your code, i just did organize the things a little bit different.

please give me feedback if anything is missing..

**Comment by ittaiz** [comment]
Thanks for your efforts in the new project/module.
The main disadvantage is that the new module needs to be released with the
current one because it's intimately familiar with the main module.
For example the latest stable of the downloaded is 1.50.5 and the latest
stable of embedded mongo is 2.0.0.
Just as an example we were planning on upgrading embedded mongo to 2.0.0
next week (currently on 1.50.5) but can't since the downloaded will
probably break.
If you are willing to release them together then it's ok for me but at
least that was the driving rationale for me.

**Comment by michaelmosmann** [comment]
ah..ok. understand...

I have no problem to release both of them.

But IMHO some can use this compiled artifact from maven central... so no need to build it by your own. Maybe we should extend the documentation a bit to make this clear....

**Comment by ittaiz** [comment]
Great, thanks! Looking forward to 2.0.0  of the downloader :)
> But IMHO some can use this compiled artifact from maven central... so no need to build it by your own. Maybe we should extend the documentation a bit to make this clear....

Not sure I understand, I'm planning on using the compiled artifact from maven central. I definitely don't want to build it myself.

**Comment by michaelmosmann** [comment]
I did a release of the 2.0.0 version (is in central in the next 24 hours)...  There was no API-Change, so this was very easy:)

But you should not forget: as long as the effekt is the same (for a version and a platform the tool downloads an artifact an put it into the cache dir) you can use any working version of this tool... no matter if your project is using embed-mongo with a newer version than that. So we have to release this tool not as often:)

**Comment by ittaiz** [comment]
I agree, It's just that often I don't know if there were incompatible
changes or not.
Thanks!

**Pull request closed without merging**
