### PR TITLE
Support for Linux ARM64/Aarch64 and for newer Mongodb versions

### PR DESCRIPTION
**Pull request by martin-g**

### CODE REVIEW

**Comment by martin-g** [comment]
I've updated .travis.yml to test on Linux AMD64, Linux AARCH64 and MacOS AMD64 but it will fail until the dependency to flapdoodle.process is -SNAPSHOT.

**Comment by martin-g** [comment]
Some unit tests fail on Linux ARM64 because they test old versions of MongoDB which do not support ARM64.
I'll try to solve this with a new Feature.

**Comment by martin-g** [comment]
The unit tests pollute the TEMP folder.
After running the unit tests there are many `extract${UUID}extractmongo${XYZ}` files in my /tmp/ folder. Most of them are 30-50M in size. After many runs of the tests my /tmp mount (16G) goes out of disk space. 
Should those be deleted after usage ?

**Comment by michaelmosmann** [comment]
> Should those be deleted after usage ?

yes for sure..
maybe there are more things to refactor:)

**Comment by michaelmosmann** [comment]
i will merge this if i change to de.flapdoodle.embed.process:3.1.2 ..

**Comment by martin-g** [comment]
Please give me few more hours to improve the tests for ARM64!

**Comment by martin-g** [comment]
Duh. It is getting more complex.
With https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/pull/343/commits/a6d52c1a8f216ffcccb583b79a6b049289b5f6b7 I've added a check for the minimal Mongodb version that supports ARM64.

With this the test passes on Ubuntu 16.04 (Xenial) but fails on 20.04 (Focal) because Mongodb 3.x depends on OpenSSL 1.0 but Ubuntu 20.04 provides OpenSSL 1.1. Trying to start Mongod fails with missing libcrypto.so.1.0.0 and libssl.so.1.0.0.
Trying to cheat by symlinking to the .so.1.1.0 versions then fail with errors like:
```
[mongod error]/tmp/extract-da4fd43c-2fe9-4614-a673-15af8d9c3c84extractmongod: /usr/lib/aarch64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /tmp/extract-da4fd43c-2fe9-4614-a673-15af8d9c3c84extractmongod)
```

**Comment by martin-g** [comment]
I think I am ready with my changes here. Apache Drill build passes with 3.0.1-SNAPSHOT on Linux ARM64!

Now I face https://github.com/wix/wix-embedded-mysql/issues/209

**Pull request merged**
