### PR TITLE
Updates dependencies and Mongo versions

### PR DESCRIPTION
**Pull request by adamretter**
* Uses the new de.flapdoodle.embed.process that was just released (2.0.3)
* Adds support for the newer versions of MongoDB
* Updates various Maven dependencies and plugins to latest versions
* Fixes transient dependency issues.

I haven't been able to run the test suite locally, as I have a very slow Internet connection at the moment. I am trusting Travis to take care of this.

If this PR is acceptable, I would really appreciate a release ASAP. As we need these changes in an upstream project. Thanks Adam.

### CODE REVIEW

**Comment by adamretter** [comment]
@dizzzz this should be the final piece of the puzzle for https://github.com/joelittlejohn/embedmongo-maven-plugin/issues/44 and your https://github.com/weXsol/Mongrel/ build.

**Comment by dizzzz** [comment]
image

**Comment by adamretter** [comment]
@dizzzz indeed. MomgoDB changed the download path and URL format for newer releases, I can
make some fixes for this soon (I'm away from the computer this afternoon I'm afraid).

**Comment by dizzzz** [comment]
@adamretter no worries

**Comment by Loki-Afro** [comment]
I cherry-picked your commits partly.
Especially I removed Version.3.7 since this is effectively  Version.DEVELOPMENT / Version.LATEST_NIGHTLY

**Comment by adamretter** [comment]
@Loki-Afro Thanks very much. I think there were a couple important changes that were not cherry-picked though which fix subtle problems with the build. I have placed those into a new PR here - https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/pull/249

**Pull request closed without merging**
