### PR TITLE
Additional options for mongo.

### PR DESCRIPTION
**Pull request by smecsia**
Hi guys. We've incorporated some of our changes into this PR. 
* Actualize versions to current MongoDB releases.
* Add the additional config options for mongo and mongod (authorization, database name, replica set options). 
* Support for the `storageEngine` option.

#115  partly resolves our needs, but not all of them.

P.S. Sry for the different indentation style. We're using default IDEA configuration and auto formatting. It's painful to turn it off.
P.P.S. We cannot use embedded mongo without these options, so we have to use our own fork for now. It would be great if you merge this PR or implement such features in the following releases.

### CODE REVIEW

**Comment by smecsia** [comment]
I've merged the changes from #118 to fix the build.

**Comment by matlockx** [comment]
thank you very much for your contribution, looks good so :+1: from my side.
@michaelmosmann wdyt?

**Comment by michaelmosmann** [comment]
I will not have enough time in the next days.. So do whatever you think is the right thing to do:) we can always change/fix things with an other release..

Am 4. April 2015 07:25:34 MESZ, schrieb "Martin Jöhren" <notifications@github.com>:
>thank you very much for your contribution, looks good so :+1: from my
>side.
>@michaelmosmann wdyt?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/pull/117#issuecomment-89507566

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by pete-experimenter** [comment]
Gents, where can I find an example of configuring auth?

**Comment by smecsia** [comment]
@pete-experimenter our project https://github.com/yandex-qatools/embedded-services uses this feature. You can take a look.

**Comment by pete-experimenter** [comment]
Thanks! The below did the trick
```
        MongoEmbeddedService mongoService = new MongoEmbeddedService(
                "localhost:9992",
                "mobile_registration_test",
                "mongodev",
                "mongodev",
                "localreplica"
        );
```
Had to remove transitive dependency though.
```
        <dependency>
            <groupId>ru.yandex.qatools.embed</groupId>
            <artifactId>embedded-services</artifactId>
            <version>1.19</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
Nice one!

**Pull request merged**
