### PR TITLE
mongodb 3.4

### PR DESCRIPTION
**Pull request by Loki-Afro**
This fixes gh-185

### CODE REVIEW

**Comment by michaelmosmann** [comment]
did it slightly different.. but thanks for your work. :+1:

**Comment by Loki-Afro** [comment]
looks even better, did not know about all corner cases :D

**Comment by michaelmosmann** [comment]
@Loki-Afro can not answer your email... get a strange 'invalid DNS MX or A/AAAA resource record.'

**Comment by Loki-Afro** [comment]
@michaelmosmann sounds strange, @pluhmen is fixing this :D

**Comment by pluhmen** [comment]
Hi @michaelmosmann 
I'm the administrator of kaffeekrone.de

You are using 1und1 (united internet web.de, gmx.de) as mail provider and they suck in such many ways... They check if a MX-Record is A or AAAA-Record. In our case we are using a CNAME for convinience and this hits their rules. None of the big Mail-Providers cares, no RFC requires that, but they do! oO

Here is a blog entry of Peer Heinlein about this issue: https://www.heinlein-support.de/blog/mailserver/gmx-blockt-e-mail-adressen-ohne-aaaaa-record/

And here's their FAQ entry: https://help.1and1.com/e-mail-and-office-c37589/1and1-mail-basic-c37590/troubleshooting-c85089/mail-delivery-failed-message-550-error-a792617.html

I've changed the CNAME to a A-Record and added a AAAA-Record 
Tomorrow it should work. Greets!

**Comment by pluhmen** [comment]
A first test shows that e-mails from and to united "internet" work again.

**Comment by michaelmosmann** [comment]
Works now.. interesting. Thanks:)

Mit AquaMail Android
http://www.aqua-mail.com gesendet


Am 26. Januar 2017 11:55:04 nachm. schrieb pluhmen <notifications@github.com>:

**Pull request closed without merging**
