### PR TITLE
Add support for MongoDB 4.2 (resolves #295)

### LINKED ISSUE #295: Support for MongoDB 4.2
Mongo has changed the binary download options and file name format in a way the breaks the embed.mongo downloader.

1. For Windows, 2012plus in now the only option. [Feature.java](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/02d644905f0b05463be31daddcf468b1b7cb6e43/src/main/java/de/flapdoodle/embed/mongo/distribution/Feature.java) needs a new value: `ONLY_WINDOWS_2012_SERVER`, and the corresponding logic in [Paths.java](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/02d644905f0b05463be31daddcf468b1b7cb6e43/src/main/java/de/flapdoodle/embed/mongo/Paths.java) needs to be implemented.
2. The generic Linux archive has been removed. There are now various distribution-specific tar files. Perhaps the RHEL 6.2 version can be used as a generic one (`mongodb-linux-x86_64-rhel62-4.2.0.tgz`).

Those were the main issues I noticed at first glance, there might be others as well.

### PR DESCRIPTION
**Pull request by zer0keefie**
I kind of needed 4.2 support, so I poked at things enough to get it working. My team develops on Windows (either 7 or 10) and the CI builds happen on CentOS 7, so I have at least those working. I picked the rhel7 build for Linux mainly because I didn't have a good way to detect the specific flavor in use.

Some notes:
- 4.2.2 wouldn't start with either --noprealloc or --smallfiles, so I disabled them with feature flags.
- Windows packages seem to also be available via fastdl.mongodb.org, so I removed the override for those.

Fixes #295

### CODE REVIEW

**Comment by keeratsingh** [comment]
@Loki-Afro  Did you get a chance to review the changes? Or is there something else expected before this reviewed and merged?

**Comment by zer0keefie** [comment]
One of my team members decided they were going to use Ubuntu, so I ended up writing some OS detection code. This worked on RHEL7, CentOS7, Ubuntu 19.09, and a version of Mint (I don't recall which one, specifically). "Worked", in this case, means MongoDB started up and was usable.

**Comment by jklappenbach** [comment]
4.2 support would be awesome.  Any movement on this?

**Review by rgavhale123 — APPROVED** [review]

**Comment by g2nconnell** [comment]
I add here some details regarding supporting MongoDB 4.2 and up.
1. Download file name for MacOS has changed as of 4.2.
Depending on the "features", for macos the generated file name to download becomes:
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-4.4.1.tgz
https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-4.4.1.tgz
Notice the "-osx-" in the filename. However, mongoDB now names the files as
mongodb-macos-x86_64-4.4.1.tgz.  So, "-macos-" instead of "-osx-" in the file name.  If you would, please add support for this.
2. Unable to start the mongod process (via embedmongo-maven-plugin) because the generated command line args includes --noprealloc.  The reason is that the command line arg --noprealloc was removed in version 4.2  Here's the entry from the command line:
[mongod error]Error parsing command line: unrecognised option '--noprealloc'

I have not found a way to not generate this flag. This prevents using embedmongo-maven-plugin with anything over mongoDB versions 4.0.x
It would be most helpful if flapdoodle would not generate the --noprealloc when using version 4.2 or greater.

**Comment by michaelmosmann** [comment]
.. that mongodb does not provide these old packages (windows, linux, macos) is kind of a pain..
Maybe we need some kind of enhanced platform detection which then could be mapped to the right artifact..

**Comment by michaelmosmann** [comment]
It now should work.. please use the new release (3.2.0) and test if it is working as expected. Thank you for your time and energy:)

**Pull request closed without merging**
