### PR TITLE
Updates 2

### PR DESCRIPTION
**Pull request by adamretter**
* Fixes transient dependencies issues in the build
* Updates plugins and dependencies to the latest versions.

### CODE REVIEW

**Comment by Loki-Afro** [comment]
where does this fix any problem? I will not update any maven plugin since via PR,  I am not 100% sure what the results are when releasing the artefact which I don't have any permission to do so :/

**Comment by adamretter** [comment]
@Loki-Afro Okay so if we ignore the updates for plugins and dependencies. Then the concrete problem that this fixes is (commits 14e21a4 and 
c9a3143):

1. There are three compile time dependencies in your Java code on:
    1. `slf4j-api`: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/test/java/de/flapdoodle/embed/mongo/MongoExecutableTest.java#L28 amongst many others.
    2. `commons-lang3`: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/test/java/de/flapdoodle/embed/mongo/buildsupport/ExtractMarkdownFromCode.java#L35.
    3. `hamcrest-core`: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/test/java/de/flapdoodle/embed/mongo/MongoDumpExecutableTest.java#L28.

    However these are not declared in your `pom.xml`.

    The reason that you are able to compile and build your code at all, is that other dependencies that you do have in your `pom.xml`, have those 3 artifacts as dependencies themselves. This is known as a `transitive dependency`. This is a problem, as your `pom.xml` is not declaring all of its required dependencies.

    My commit 14e21a4, fixes these transitive dependency problems by explicitly declaring the libraries that your code has a dependency on.

2. There is a mechanism in Maven to detect, report and allow you to fix such *transitive dependency* problems. You can use the `analyze` mechanism of the Dependency plugin.

    My commit c9a3143 enables this as part of the build, so that the build will fail and alert you if it detects transitive dependency problems in future. In fact, if you were to just apply this commit and run the build, you would see the transitive dependency failures that 14e21a4 fixes.

Hope that makes sense? Let me know if you need further clarification...

**Comment by adamretter** [comment]
@Loki-Afro Any thoughts on my response?

**Comment by Loki-Afro** [comment]
@adamretter I know how maven works but thanks ;)

declaring transivie dependencies again seems very odd since we have also control over the the process library.

>  This is a problem, as your pom.xml is not declaring all of its required dependencies.
It is not a problem at all.

**Comment by adamretter** [comment]
@Loki-Afro I was just pointing out the problems as they seemed to have been missed. Of course ultimately it's up to you guys. Cheers.

**Pull request closed without merging**
